number = 8
slug = "list-syntax-and-builtins"
status = "completed"
description = """
Add list syntax to the parser AND hd/tl/is_empty built-ins.

Lexer:
- Add TK_..."""
role = "production"
context_files = []
created_at = "2026-04-14T18:15:58"
completed_at = "2026-04-14T18:45:04"
commits = ["8f7200106849d437cb6bf2a7993116de90a9aa74"]
